//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piaskownica.Pages.Button {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ButtonPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ButtonPageResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Piaskownica.Pages.Button.ButtonPageResources", typeof(ButtonPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use the &lt;span class=&quot;component&quot;&gt;KAButton&lt;/span&gt; component to render a standard HTML button tag that contains a number of commonly used parameters..
        /// </summary>
        public static string BasicExampleDescription {
            get {
                return ResourceManager.GetString("BasicExampleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use the &lt;span class=&quot;component&quot;&gt;KAButtonGroup&lt;/span&gt; wrapper to create a group of buttons. .
        /// </summary>
        public static string ButtonGroupDescription {
            get {
                return ResourceManager.GetString("ButtonGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use the &lt;span class=&quot;parameter&quot;&gt;Direction&lt;/span&gt; parameter to switch between displaying group in a row or in a column..
        /// </summary>
        public static string ButtonGroupDirectionDescription {
            get {
                return ResourceManager.GetString("ButtonGroupDirectionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Direction.
        /// </summary>
        public static string ButtonGroupDirectionTitle {
            get {
                return ResourceManager.GetString("ButtonGroupDirectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu By default, &lt;span class=&quot;component&quot;&gt;KAButtonGroup&lt;/span&gt; wrapper doesn&apos;t force the buttons to conform to a single style setting. However one may set &lt;span class=&quot;parameter&quot;&gt;Color&lt;/span&gt;, &lt;span class=&quot;parameter&quot;&gt;Size&lt;/span&gt; or &lt;span class=&quot;parameter&quot;&gt;Type&lt;/span&gt; parameters to forcefully override the individual button styles..
        /// </summary>
        public static string ButtonGroupOverridesDescription {
            get {
                return ResourceManager.GetString("ButtonGroupOverridesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Overrides.
        /// </summary>
        public static string ButtonGroupOverridesTitle {
            get {
                return ResourceManager.GetString("ButtonGroupOverridesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu KAButtonGroup.
        /// </summary>
        public static string ButtonGroupTitle {
            get {
                return ResourceManager.GetString("ButtonGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use the &lt;span class=&quot;parameter&quot;&gt;Color&lt;/span&gt; parameter to change the color of the button..
        /// </summary>
        public static string ColorDescription {
            get {
                return ResourceManager.GetString("ColorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color.
        /// </summary>
        public static string ColorTitle {
            get {
                return ResourceManager.GetString("ColorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You may set only one of the icons to render an icon button..
        /// </summary>
        public static string IconButtonDescription {
            get {
                return ResourceManager.GetString("IconButtonDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Icon button.
        /// </summary>
        public static string IconButtonTitle {
            get {
                return ResourceManager.GetString("IconButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use the &lt;span class=&quot;parameter&quot;&gt;StartIcon&lt;/span&gt; and &lt;span class=&quot;parameter&quot;&gt;EndIcon&lt;/span&gt; parameters to set the icons that appear before and after the button&apos;s text. You can use either one of them or both at the same time..
        /// </summary>
        public static string IconsDescription1 {
            get {
                return ResourceManager.GetString("IconsDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The value you provide is passed on to the &lt;span class=&quot;component&quot;&gt;KAIcon&lt;/span&gt; component, so it follows the same rules that apply for that parameter in that component..
        /// </summary>
        public static string IconsDescription2 {
            get {
                return ResourceManager.GetString("IconsDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Icons.
        /// </summary>
        public static string IconsTitle {
            get {
                return ResourceManager.GetString("IconsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use the &lt;span class=&quot;parameter&quot;&gt;Size&lt;/span&gt; parameter to change the size of the button..
        /// </summary>
        public static string SizeDescription {
            get {
                return ResourceManager.GetString("SizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Size.
        /// </summary>
        public static string SizeTitle {
            get {
                return ResourceManager.GetString("SizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu By default, the &lt;span class=&quot;component&quot;&gt;KAButton&lt;/span&gt; component sets the value of &lt;span class=&quot;attribute&quot;&gt;type&lt;/span&gt; attribute to &lt;span class=&quot;value&quot;&gt;button&lt;/span&gt; value. One may change it by simply setting the attribute like any other component parameter..
        /// </summary>
        public static string TypeAttributeRemark {
            get {
                return ResourceManager.GetString("TypeAttributeRemark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Use the &lt;span class=&quot;parameter&quot;&gt;Type&lt;/span&gt; parameter to change the variant of the button..
        /// </summary>
        public static string TypeDescription {
            get {
                return ResourceManager.GetString("TypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Type.
        /// </summary>
        public static string TypeTitle {
            get {
                return ResourceManager.GetString("TypeTitle", resourceCulture);
            }
        }
    }
}
